[source]
mqtt_host = "localhost"
mqtt_port = 1883
topics = ["test/#"]

[destination]
mqtt_host = "localhost"
mqtt_port = 1883

[cache]
path = "/tmp/persistmq"

# Settings for bulk transfer of messages, if cache is above msg_count.
[bulk_messages]
bulk_msg_count = 100
bulk_topic_rewrite = "mixed/cbor"
