[source]
mqtt_host = "localhost"
mqtt_port = 1883
topics = ["private/#"]

[destination]
mqtt_host = "mqtt.pqopen.com"
mqtt_port = 8883
use_tls = true # enable tls
username = "your-mqtt-password"
password = "your-mqtt-password"
client_id = "your-device-id"

[cache]
path = "/tmp/persistmq"